apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anime.fullname" . }}-secret
type: Opaque
stringData:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}