apiVersion: v1
kind: Service
metadata:
  name: {{ include "anime.fullname" . }}
  labels:
    {{- include "anime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "anime.selectorLabels" . | nindent 4 }}
